### ISSUE TITLE
ModuleNotFoundError: No module named 'sfo.sfo'

### ISSUE THREAD

**Issue by stripnwild** [Zer0xFF/PS4_db_rebuilder#5] opened 2020-01-07 16:38 UTC
ran the ps4_db_rebuilder-0.1  and it semed to work but this time through  games on the external HD didnt work?  So I downloaded the realease_0.1_EXTERNAL  and extracted to my desktop.  brought up the administrator CMD and entered fix_db.py 192.168.0.187 and this is what comes up?

"ModuleNotFoundError: No module named 'sfo.sfo'

**Comment by Zer0xFF** [comment] 2020-01-11 10:01
dont run it as admin, there is no point, I as far as im concern, games on externa HDD woould show up by themselves , no actions needed.

I dont recall release any *external* fixers, so no support would be provided for that.
this is a duplicate of #2 so closing. (you can read for relevant info as well)

**Closed as completed by Zer0xFF** 2020-01-11 10:01 UTC
